### PR TITLE
Fixes for Command-Line options are case sensitive

### PR DESCRIPTION
**Pull request by naveensrinivasan**
These are fixes for the command line options being case insensitive #251. The
fixes should work for the argument and switches.
Example
``` 
InstAll --ManuAl
```

### CODE REVIEW

**Comment by TravisTheTechie** [comment]
We've avoiding including NuGet in the repo purposefully. I'm not sure if we want to revert that decision.

**Comment by TravisTheTechie** [comment]
:+1: on the code changes themselves though.

**Comment by naveensrinivasan** [comment]
Thanks, could you please let me know what is the reason behind avoiding  including NuGet in the repo?

**Comment by TravisTheTechie** [comment]
Yeah, we just look to avoid including binaries in the repo. It bloats the repo and isn't needed for most cases -- you will likely have nuget installed on your machine in some fashion. 

While this might not be the case for mono development, I don't think we're to the point of making this change to just support that use case.

**Comment by phatboyg** [comment]
I cherry-picked the case sensitivity commit.

**Comment by naveensrinivasan** [comment]
So could I close thi PR?

**Comment by phatboyg** [comment]
I haven't because I want to get some of the build bits to convert to appveyor. 

____
Chris Patterson

**Comment by phatboyg** [comment]
command line fix was picked a while back, the build is now on appveyro so closing.

**Pull request closed without merging**
