### PR TITLE
Remove some conditional compile for NETCORE

### LINKED ISSUE #568: "Topshelf install start"(install and start) is broken in netcore version
Tested with `4.2.1` and `4.2.1.218-develop` in netcoreapp3.1.
According to the doc for Topshelf, `start` is one possible option of `install`, and mean:              Start the service after it has been installed.

But in netcore version, the command seems be just parsed as `start`, and always failed with `StartHost ERROR The CH.Smart.Comm service is not installed.`

### PR DESCRIPTION
**Pull request by yyjdelete**
Fix #568

### CODE REVIEW

**Comment by yyjdelete** [comment]
Verified #568 is fixed with the changed in `StartBuilder.cs`

I don't know why code in `ConfigurationExtensions.cs` is disabled, and how to test it, but enable it didn't lead to compile error.

**Comment by phatboyg** [comment]
Did you verify that Topshelf work with the new build? Compiles != It works.

**Comment by yyjdelete** [comment]
@phatboyg 
Topshelf.Extensions.Configuration/ConfigurationExtensions.cs
> ***NOT TESTED***, I never use `Topshelf.Extensions.Configuration` before and not sure how to do test with it. But it should be OK since all new enabled code only reference already exists public api in `Topshelf` (expect `ServiceRecoveryOption` below), and should. And it also dangerous to make it silently ignore some config without any WARNS on different platform, and may lead to unexpected behavior.

Topshelf/Configuration/Builders/StartBuilder.cs
> VERIFIED. that works for me in netcoreapp3.1/2.1(windows) with my service, fix for #568.

Topshelf/Configuration/Options/ServiceRecoveryOption.cs
> ***NOT DIRECTLY TESTED***. Seems it's only used by `ConfigurationExtensions`, and is an simple wrapper of 
another public api ServiceRecoveryHostConfigurator, and the latter one is used as  as `EnableServiceRecovery() in `SampleTopshelfService` and  works well in netcoreapp2.1/3.1(windows)

Topshelf/Hosts/ConsoleRunHost.cs 
> VERIFIED. Tested in windows with netcoreapp3.1/2.1(windows), add back catch for `IOException` in netcore, and also catch for `PlatformNotSupportedException` for some special platform, also do check with `GetConsoleWindow` when `IsOSPlatform(OSPlatform.Windows)` is true(netcoreapp3.x+ can modify `<OutputType>WinExe</OutputType>` to disable console)

**Comment by yyjdelete** [comment]
All changes except `ConsoleRunHost.cs` maybe related to 77548a22509bc21e1fc8e8f8bac99735bf0765b8, since they are added when installer is not available for netcore.

**Pull request merged**
