### PR TITLE
Updated Serilog to v2

### PR DESCRIPTION
**Pull request by madhon**
Updating Serilog to v2, should sort out #342 and #346

---
This change is [Reviewable](https://reviewable.io/reviews/topshelf/topshelf/348)

### CODE REVIEW

**Comment by TravisTheTechie** [comment]
Build fails for this.

**Comment by jwhitex** [comment]
@TravisTheTechie Any ideas why this won't build? 

[Relevant?](http://stackoverflow.com/questions/38705868/serilog-already-has-a-dependency-defined-for-microsoft-csharp)

**Comment by jwhitex** [comment]
See - [Point nuget.exe source uri to latest;](https://github.com/jwhitex/Topshelf/commit/b053bf7113563477c1e986c1c96ca14a9db620ab)

Can update to serilog v2 locally with above change.

@TravisTheTechie Is this a pr you would accept?

**Comment by phatboyg** [comment]
Yeah, if we can get it to build...

**Pull request closed without merging**
