### PR TITLE
Update quickstart documentation to include details about capturing and returning service exit code

### PR DESCRIPTION
**Pull request by FireEater64**
Addresses issue raised in #104 by @piers7.

### CODE REVIEW

**Comment by TravisTheTechie** [comment]
I can see this being useful; but is this important for getting start? My first thought is that we have should have this in it's own section since you don't NEED it to get started.

**Comment by piers7** [comment]
Quickstart should reflect minimum best practice, to make easiest for newbies and cut/paste fans to fall into the pit of success. You should always do this, to ensure failed installs are detected correctly. Ergo it should be in the quickstart.

**Comment by FireEater64** [comment]
@TravisTheTechie Happy to rewrite it any which way you'd like. I'd personally agree with @piers7 though - it's certainly something that burned me the first time I used TopShelf.

**Comment by TravisTheTechie** [comment]
Alright -- I admit I'm a bit disconnected from getting started, so I'll take that feedback. 

Let's get the whitespace (trailing spaces, changes in indentation depth of comments) cleaned up and I'll merge it.

**Pull request merged**
