### PR TITLE
fixes #193: WindowsServiceRecoveryController fails: Failed to change service recovery options

### LINKED ISSUE #193: WindowsServiceRecoveryController fails: Failed to change service recovery options
If a user has UAC turned on, and attempts to install a service that has RestartComputer set as one of the service recovery options, the install fails.
This is because, even with the --sudo option, the process needs explicit SE_SHUTDOWN_NAME privileges before calling the ChangeServiceConfig2 API.
Pushing PR shortly.

### PR DESCRIPTION
**Pull request by pianomanjh**

### CODE REVIEW

**Comment by eggapauli** [comment]
@pianomanjh Any progress on this? We would need this as well.

**Comment by haf** [comment]
@eggapauli If you try out the branch/PR and tell us it's good, then we'll merge =)

**Comment by pianomanjh** [comment]
I updated to use a safe token handle, but did not have time to test today. @eggapauli or @haf, can you check this change?

**Comment by eggapauli** [comment]
I just tried it and for me this works, thanks.

**Comment by phatboyg** [comment]
FYI, I reverted this commit and am putting it into develop behind all the other develop commits that were well ahead of it.

For future reference, we only merge rebased commits onto develop until they are released.

**Pull request merged**
