### PR TITLE
Fixes issue #237: Update Nlog version to 4.1.2

### PR DESCRIPTION
**Pull request by tomikiss**
Migrate all method matching the new Nlog v4 API for logging exceptions.

### CODE REVIEW

**Comment by tomikiss** [comment]
These are fixes for case #237

**Comment by phatboyg** [comment]
went past to 4.2.2

**Comment by tomikiss** [comment]
Sorry your latest commit haven't changed the signature of the calls therefore exception won't  be logged correctly.

**Comment by phatboyg** [comment]
Yeah, I see that. I updated this now and re-released.

**Pull request closed without merging**
