### PR TITLE
Make ExitCodes an enum again

### PR DESCRIPTION
**Pull request by BlythMeister**

### CODE REVIEW

**Comment by maxcherednik** [comment]
@BlythMeister which problem you are trying to solve now?

**Comment by BlythMeister** [comment]
Reability and simplicity of the code...this was a struct that behaved like an enum.
So why not just actually be an enum.

**Comment by BlythMeister** [comment]
Also this comment suggested making it an enum again...https://github.com/Topshelf/Topshelf/commit/d47f7a17312a7d35ce012eb10b3c0c7039914f67#commitcomment-30734708

**Comment by maxcherednik** [comment]
> Also this comment suggested making it an enum again...[d47f7a1#commitcomment-30734708](https://github.com/Topshelf/Topshelf/commit/d47f7a17312a7d35ce012eb10b3c0c7039914f67#commitcomment-30734708)

This was solved shortly after.

**Comment by BlythMeister** [comment]
Feel free to close this, but as someone external looking at this code for the 1st time, I was baffled as to why use a struct over an enum.
The usage syntax is exactly the same, thus, the intent is the same.
This also follows a similar usage pattern the the system.net httpstatuscode enum which does not specify every http status code, but allows for additional codes to be used.
Here are the arguments put much more elequantly than me by Jon Skeet https://stackoverflow.com/a/13429174/1780951

**Pull request merged**
