### PR TITLE
CI using appveyor

### PR DESCRIPTION
**Pull request by naveensrinivasan**
Here is a simple continuous integration using appveyor. This would
enable appveyor builds.

### CODE REVIEW

**Comment by phatboyg** [comment]
Nice, I'll work on pulling these in soon.

**Comment by DustinVenegas** [comment]
Any word on an AppVeyor build? I'm curious about this, the FAKE scripts, and some documentation. I've been thankfully using TopShelf quite a bit more lately.

**Comment by phatboyg** [comment]
I have MassTransit and Automatonymous on Appveyor. I just need to move Topshelf. I'll likely drop all pre-4.5 support at that time.

**Comment by KevM** [comment]
:cry:  Dropping pre 4.5 support?

**Comment by phatboyg** [comment]
Yes. The existing code does plenty for the .NET 4 and earlier code. Just going to make the next 4.x release only support he newest frameworks including hopefully coreclr

**Comment by KevM** [comment]
Well if I can help keep things supported on .Net 4 I am happy to help. My world still supports [POS Ready 2009](https://en.wikipedia.org/wiki/Windows_Embedded_Industry) which is basically XP and is thus capped at .Net 4.

**Comment by phatboyg** [comment]
It's likely that the oldest .NET 4 will be supported. Since there is no asynchronous code in Topshelf.

**Comment by KevM** [comment]
:+1: Issue hijack aborted.

**Comment by phatboyg** [comment]
This is all done now, develop is fully CI integrated.

**Pull request closed without merging**
