### PR TITLE
Update Serilog to v2;

### PR DESCRIPTION
**Pull request by jwhitex**
Version Matches MassTransit.SerilogIntegration Serilog version. Resolves #348, #342, and #346.

### CODE REVIEW

**Comment by jwhitex** [comment]
@phatboyg We suspect using Serilog v1 in our Topshelf project has something to do with not getting logs when exceptions are thrown in MassTransit consumers. Note that we are setting the global Log.Logger with a Serlog v1 logger and applying the UseSerilog() extension on both the bus and the service 'Configurator'.

**Comment by waynebrantley** [comment]
Any chance of getting this closed and a new build published?

**Comment by phatboyg** [comment]
Yeah, soon for sure.

**Comment by ar1k** [comment]
I think this PL needs in one more change. Because the memory buffer may contain events that have not yet been written to the target sink, it is important to call Log.CloseAndFlush(), and appropriate place is Shutdown() in [SerilogLogWriterFactory.cs](https://github.com/Topshelf/Topshelf/blob/develop/src/Topshelf.Serilog/Logging/SerilogLogWriterFactory.cs). Hope this request will be accepted soon after that :)

**Comment by phatboyg** [comment]
Sounds good to me. Will get to this after the vs2017 branch is merged.

**Comment by ar1k** [comment]
@phatboyg, Is there any chance that the request will be accepted soon?

**Comment by stefanopretto** [comment]
@phatboyg I second the request, I would really love to be able to use the latest Serilog version with Topshelf.

**Comment by stephenpatten** [comment]
@phatboyg  is the goal to be backwards compatible, or is this a nuget issue?

**Comment by phatboyg** [comment]
I'll get it merged soon. I need to update Topshelf anyway.

**Comment by stephenpatten** [comment]
Much appreciated.

**Comment by stephenpatten** [comment]
I'm will to help with this, let me know how.

**Pull request closed without merging**
